/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;

/**
 * Atividade referente ao jogo do gênio
 * @author Moisés Dourado 
 */
public class JogoGenio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JogoGenio.class.getName());

    /**
     * Creates new form JogoGenio
     */
    public JogoGenio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFrase = new javax.swing.JLabel();
        lblGenio = new javax.swing.JLabel();
        txtValor = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFrase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/bubble-chat (1).png"))); // NOI18N
        lblFrase.setText("<html><center>Vou pensar em um<br>valor entre 1 e 5...</center></html>");
        lblFrase.setToolTipText("");
        lblFrase.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 290, 200));

        lblGenio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade04/images/genie (1).png"))); // NOI18N
        lblGenio.setToolTipText("");
        getContentPane().add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        txtValor.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        btnPalpite.setText("Adivinhe:");
        btnPalpite.addActionListener(this::btnPalpiteActionPerformed);
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
    // 1. Gera um numero inteiro aleatorio entre 1 e 5
    int n = new java.util.Random().nextInt(5) + 1;

    // 2. Captura o palpite escolhido pelo usuario no JSpinner
    int palpite = Integer.parseInt(txtValor.getValue().toString());

    // 3. Usa o Operador Ternario para definir o texto do resultado
    String resultado = (palpite == n) ? "<html><center>ACERTOU!</center></html>" : "<html><center>ERROU!<br>Pensei no " + n + "</center></html>";

    // 4. Joga o resultado na tela e altera a fonte
    lblFrase.setText(resultado);
    lblFrase.setFont(new java.awt.Font("Arial Black", java.awt.Font.PLAIN, 16));
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JogoGenio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JSpinner txtValor;
    // End of variables declaration//GEN-END:variables
}
